移动行为:

  冲刺:
    # 控制冲刺的距离, 支持小数
    行动强度: 1.0

    # 消耗的体力值
    所需体力: 5

  二段跳:
    # 控制二段跳的高度
    行动强度: 0.5
    # 控制二段跳时玩家往前跳的力度
    冲刺力度: 1.0
    # 消耗的体力值
    所需体力: 10
    # 开启摔落伤害会导致二段跳难度增加, 一般需要按三下空格才能成功二段跳, 且仅支持 paper 系服务端
    摔落伤害: false

体力恢复设置:
  # 当玩家停止消耗体力多长时间时开始恢复体力? 1000 毫秒 = 1 秒, 现在是 1.5 秒
  恢复间隔: 1500
  # 每 2tick 恢复 1 体力值(最低为1, 越低恢复越快, 越高越慢)
  恢复速度: 2


体力上限设置:
  # 默认体力值 15, 默认玩家拥有的体力值
  default: 15
  # vip1 体力值, 权限 sakuramove.stamina.vip1
  vip1: 20
  # vip2 体力值, 权限 sakuramove.stamina.vip2
  vip2: 25
  vip3: 30
  # svp 体力值, 权限 sakuramove.stamina.svp
  svp: 35
  mvp: 40

Message:
  Reload: "&9&lSakuraMove &6&l>> &a插件已重载"